[0m20:04:08.430457 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f28e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f46ab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f46510>]}


============================== 20:04:08.433051 | 99a70704-5a1c-4604-9b82-155495e05a55 ==============================
[0m20:04:08.433051 [info ] [MainThread]: Running with dbt=1.9.1
[0m20:04:08.433380 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/gms4/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init my_dbt_project', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:04:08.438184 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/gms4/.dbt')}
[0m20:04:08.438422 [info ] [MainThread]: Creating dbt configuration folder at 
[0m20:04:08.439105 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/include/starter_project
[0m20:04:08.441850 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:04:08.442035 [info ] [MainThread]: Setting up your profile.
[0m20:05:33.416723 [info ] [MainThread]: Profile my_dbt_project written to /Users/gms4/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m20:05:33.461448 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 85.09193, "process_in_blocks": "0", "process_kernel_time": 0.134264, "process_mem_max_rss": "97419264", "process_out_blocks": "0", "process_user_time": 0.723489}
[0m20:05:33.462376 [debug] [MainThread]: Command `dbt init` succeeded at 20:05:33.462219 after 85.09 seconds
[0m20:05:33.463042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107562120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108efc650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f70a70>]}
[0m20:05:33.463632 [debug] [MainThread]: Flushing usage events
[0m20:05:34.487939 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:39:52.329007 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052e3020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062a2f30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062a2ab0>]}


============================== 21:39:52.332261 | b99a1920-a704-491e-a79d-06e4b948181a ==============================
[0m21:39:52.332261 [info ] [MainThread]: Running with dbt=1.9.1
[0m21:39:52.332609 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/gms4/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:39:52.332912 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gms4/Desktop/guilherme/TCC/Project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:39:52.334298 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.06678233, "process_in_blocks": "0", "process_kernel_time": 0.13968, "process_mem_max_rss": "92160000", "process_out_blocks": "0", "process_user_time": 0.641316}
[0m21:39:52.334529 [debug] [MainThread]: Command `dbt run` failed at 21:39:52.334483 after 0.07 seconds
[0m21:39:52.334728 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062a2c30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062a2d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062a2bd0>]}
[0m21:39:52.334898 [debug] [MainThread]: Flushing usage events
[0m21:39:53.340723 [debug] [MainThread]: An error was encountered while trying to flush usage events
